### ISSUE TITLE
https://github.com/purpleidea/mgmt

### ISSUE THREAD

**Issue by gedw99** [choria-io/go-backplane#34]
This uses a graph to map code together so its reactive.

Reminds me a bit of what your doing, but using NATS.

https://github.com/purpleidea/mgmt

Figured its worth just listing here as there is heavy crossover in that this is meant to replace Puppet

**Comment by ripienaar** [comment]
Yeah I know him well - say talking at confs a lot :)

**Comment by ripienaar** [comment]
Fwiw here is a shitty video of backplane in use https://youtu.be/tEI2xEi0llM

Sorry about computer voice. Can’t go somewhere without noise now

**Comment by gedw99** [comment]
the Voice is hilarious :)

**Comment by gedw99** [comment]
Its a great intro to what how why of the sytem.
Can you link to the code ?

**Comment by ripienaar** [comment]
the initial vagrant code is in this repo - example - the other is a closed system

**Comment by ripienaar** [comment]
What I need to finish - and the I'll make a full video is that you can do from ruby:

```ruby
require "mcollective"

include MCollective::RPC

c = rpcclient("backplane")
c.collective = "cron_backplane"
c.pause
```

and it'll pause all the machines, also a go client and also from these things https://choria.io/docs/playbooks/

also a ruby cli automatically `mco rpc backplane pause -T cron_backplane` and lots of ways to filter down to subsets of the nodes - say per DC etc

**Comment by gedw99** [comment]
I will wait until your done with your example...

**Comment by gedw99** [comment]
think i should close this now...

**Comment by ripienaar** [comment]
The example is done, you can run it today with `docker compose up` in this repo

**Comment by gedw99** [comment]
ah ok :)
